version: "3.1"

services:
  web:
    build: .
    restart: always
    ports:
      - 2368:2368
      - 8080:8080
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    env_file: .env
    depends_on:
      - mysql
    command: bash -c "./docker-start.sh"

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
